# Generated by Django 5.2.6 on 2026-04-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('tag', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('timeline', models.CharField(max_length=50)),
                ('hours_saved_month', models.IntegerField(default=0, help_text='Number of hours saved per month')),
                ('accuracy_gain', models.FloatField(default=0.0, help_text='Percentage of accuracy gained')),
                ('throughput_gain', models.FloatField(default=0.0, help_text='Percentage of workflow throughput gain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stack', models.ManyToManyField(related_name='case_studies', to='portfolio.technology')),
            ],
            options={
                'verbose_name_plural': 'Case Studies',
                'ordering': ['-created_at'],
            },
        ),
    ]
